### ISSUE TITLE
Crash indexer.rb:539:in `exec_params'

### ISSUE THREAD

**Issue by DanRidgway** [ankane/dexter#49]
Using the latest docker image with the command 
`docker run -ti ankane/dexter postgresql://blahblah --pg-stat-statements`

```
Processing 1363 new query fingerprints
/usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:539:in 'exec_params': ERROR:  hypopg: not more oid available (PG::InternalError)
HINT:  Remove hypothetical indexes or enable hypopg.use_real_oids
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:539:in 'block in execute'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:535:in 'synchronize'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:535:in 'execute'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:604:in 'create_hypothetical_index'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:598:in 'block (2 levels) in create_hypothetical_indexes_helper'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:597:in 'permutation'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:597:in 'block in create_hypothetical_indexes_helper'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:595:in 'each'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:595:in 'create_hypothetical_indexes_helper'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:225:in 'create_hypothetical_indexes'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:99:in 'process_queries'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/indexer.rb:32:in 'process_stat_statements'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/client.rb:27:in 'perform'
        from /usr/local/bundle/gems/pgdexter-0.5.2/lib/dexter/client.rb:9:in 'start'
        from /usr/local/bundle/gems/pgdexter-0.5.2/exe/dexter:7:in '<top (required)>'
        from /usr/local/bundle/bin/dexter:25:in 'load'
        from /usr/local/bundle/bin/dexter:25:in '<main>'
```

both of these settings are set to on
hypopg.enabled
hypopg.use_real_oids

**Comment by ankane** [comment]
Hi @DanRidgway, thanks for reporting. Based on the error message and some testing, it looks like `hypopg.use_real_oids` isn't enabled in the session you're using for Dexter. You can set it on the database level with:

```sql
ALTER DATABASE mydb SET hypopg.use_real_oids = on;
```

I think the error could also be avoided by processing queries in batches instead of all at once. Will try to add this when I have a chance.

**Comment by DanRidgway** [comment]
Hi @ankane, thanks for replying. However on my AWS RDS instance using the postgres admin user I get 
`SQL Error [42501]: ERROR: permission denied to set parameter "hypopg.use_real_oids"`

AWS does not give you super user permissions nor can you access an account with it.

**Comment by ankane** [comment]
Should be fixed in the commit above. Thanks again!

**Comment by DanRidgway** [comment]
Thanks! I will give it a go later today.

**Comment by dmorel** [comment]
Hello, using 0.5.4 I still get the same error:

```text
dexter -d coredb_dev --pg-stat-statements -h localhost -U superduperadmin -p 2002 --min-time 0.2
Processing 25 new query fingerprints
/opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/indexer.rb:548:in `exec_params': ERROR:  hypopg: not more oid available (PG::InternalError)
ASTUCE : Remove hypothetical indexes or enable hypopg.use_real_oids
```
Is there a way to use hypopg.use_real_oids for the session, since I cannot set it globally (RDS instance too)?

**Comment by bdegomme** [comment]
still had the same issue with 0.5.5, but running `ALTER DATABASE mydb SET hypopg.use_real_oids = on;` did the trick for me

**Comment by bdegomme** [comment]
I have the same issue, this seems relevant https://github.com/ankane/dexter/pull/57
